# Generated by Django 4.2.5 on 2023-11-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=500, unique=True, verbose_name='Название курса'),
        ),
    ]
