# Generated by Django 4.2.5 on 2023-11-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_alter_lesson_name_alter_lesson_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название курса'),
        ),
    ]
