# Generated by Django 4.2.5 on 2023-10-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'permissions': (('modify_course', 'Can modify course content'),), 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['name'], 'permissions': (('modify_lesson', 'Can modify lesson content'),), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
