# Generated by Django 4.2.5 on 2023-11-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_alter_lesson_name_alter_lesson_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.TextField(max_length=255, verbose_name='Описание курса'),
        ),
    ]
